-- MySQL Script generated by MySQL Workbench
-- ter 26 nov 2019 13:12:57 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Armazem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Armazem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Armazem` DEFAULT CHARACTER SET utf8 ;
USE `Armazem` ;

-- -----------------------------------------------------
-- Table `Armazem`.`Produtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Produtor` (
  `idProdutor` INT(4) NOT NULL AUTO_INCREMENT,
  `CNPJ` CHAR(14) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` CHAR(11) NOT NULL,
  `dataIngresso` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idProdutor`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Endereco` (
  `idEndereco` INT(4) NOT NULL AUTO_INCREMENT,
  `CEP` CHAR(8) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Numero` VARCHAR(5) NOT NULL,
  `Complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Enderecos` (
  `idProdutor` INT(4) NOT NULL,
  `idEndereco` INT(4) NOT NULL,
  PRIMARY KEY (`idProdutor`, `idEndereco`),
  INDEX `fk_Produtor_has_Endereco_Endereco1_idx` (`idEndereco` ASC),
  INDEX `fk_Produtor_has_Endereco_Produtor_idx` (`idProdutor` ASC),
  CONSTRAINT `fk_Produtor_has_Endereco_Produtor`
    FOREIGN KEY (`idProdutor`)
    REFERENCES `Armazem`.`Produtor` (`idProdutor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Produtor_has_Endereco_Endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `Armazem`.`Endereco` (`idEndereco`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Fazenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Fazenda` (
  `idFazenda` INT(4) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Municipio` VARCHAR(100) NULL,
  `Extensao` FLOAT(6) NULL,
  `Coordenadas` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idFazenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Posse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Posse` (
  `idProdutor` INT(4) NOT NULL,
  `idFazenda` INT(4) NOT NULL,
  PRIMARY KEY (`idProdutor`, `idFazenda`),
  INDEX `fk_Produtor_has_Fazenda_Fazenda1_idx` (`idFazenda` ASC),
  INDEX `fk_Produtor_has_Fazenda_Produtor1_idx` (`idProdutor` ASC),
  CONSTRAINT `fk_Produtor_has_Fazenda_Produtor1`
    FOREIGN KEY (`idProdutor`)
    REFERENCES `Armazem`.`Produtor` (`idProdutor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Produtor_has_Fazenda_Fazenda1`
    FOREIGN KEY (`idFazenda`)
    REFERENCES `Armazem`.`Fazenda` (`idFazenda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Produto` (
  `idProduto` INT(4) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `Especificacao` TEXT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Estoque` (
  `idEstoque` INT(4) NOT NULL AUTO_INCREMENT,
  `Quantidade` FLOAT(6) NOT NULL,
  `idProduto` INT(4) NOT NULL,
  PRIMARY KEY (`idEstoque`),
  INDEX `fk_Estoque_Produto1_idx` (`idProduto` ASC),
  UNIQUE INDEX `Produto_idProduto_UNIQUE` (`idProduto` ASC),
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `Armazem`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Producao` (
  `idProducao` INT(4) NOT NULL AUTO_INCREMENT,
  `Quantidade` FLOAT(6) NOT NULL,
  `Safra` CHAR(4) NOT NULL,
  `idProdutor` INT(4) NOT NULL,
  `idFazenda` INT(4) NOT NULL,
  `idProduto` INT(4) NOT NULL,
  `idEstoque` INT(4) NOT NULL,
  PRIMARY KEY (`idProducao`),
  INDEX `fk_Producao_Produtor1_idx` (`idProdutor` ASC),
  INDEX `fk_Producao_Fazenda1_idx` (`idFazenda` ASC),
  INDEX `fk_Producao_Produto1_idx` (`idProduto` ASC),
  UNIQUE INDEX `idProdutor_UNIQUE` (`idProdutor` ASC),
  UNIQUE INDEX `idFazenda_UNIQUE` (`idFazenda` ASC),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC),
  INDEX `fk_Producao_Estoque1_idx` (`idEstoque` ASC),
  UNIQUE INDEX `idEstoque_UNIQUE` (`idEstoque` ASC),
  CONSTRAINT `fk_Producao_Produtor1`
    FOREIGN KEY (`idProdutor`)
    REFERENCES `Armazem`.`Produtor` (`idProdutor`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Producao_Fazenda1`
    FOREIGN KEY (`idFazenda`)
    REFERENCES `Armazem`.`Fazenda` (`idFazenda`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Producao_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `Armazem`.`Produto` (`idProduto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Producao_Estoque1`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `Armazem`.`Estoque` (`idEstoque`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Comprador` (
  `idComprador` INT(4) NOT NULL AUTO_INCREMENT,
  `CNPJ` CHAR(14) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Numero` VARCHAR(5) NOT NULL,
  `Complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idComprador`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Transportadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Transportadora` (
  `idTransportadora` INT(4) NOT NULL AUTO_INCREMENT,
  `CNPJ` VARCHAR(14) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Numero` VARCHAR(5) NOT NULL,
  `Complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idTransportadora`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Transacao` (
  `idTransacao` INT(4) NOT NULL AUTO_INCREMENT,
  `Valor` FLOAT(16) NOT NULL,
  `dataTransacao` DATE NOT NULL,
  `Quantidade` FLOAT(6) NOT NULL,
  `idEstoque` INT(4) NOT NULL,
  `idComprador` INT(4) NOT NULL,
  `idTransportadora` INT(4) NOT NULL,
  PRIMARY KEY (`idTransacao`),
  INDEX `fk_Transacao_Estoque1_idx` (`idEstoque` ASC),
  INDEX `fk_Transacao_Comprador1_idx` (`idComprador` ASC),
  INDEX `fk_Transacao_Transportadora1_idx` (`idTransportadora` ASC),
  CONSTRAINT `fk_Transacao_Estoque1`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `Armazem`.`Estoque` (`idEstoque`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Transacao_Comprador1`
    FOREIGN KEY (`idComprador`)
    REFERENCES `Armazem`.`Comprador` (`idComprador`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Transacao_Transportadora1`
    FOREIGN KEY (`idTransportadora`)
    REFERENCES `Armazem`.`Transportadora` (`idTransportadora`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
